#pragma once

namespace Keyboard {
    namespace Keys {
        constexpr auto VK_ESC          = 0x01;
        constexpr auto VK_1            = 0x02;
        constexpr auto VK_2            = 0x03;
        constexpr auto VK_3            = 0x04;
        constexpr auto VK_4            = 0x05;
        constexpr auto VK_5            = 0x06;
        constexpr auto VK_6            = 0x07;
        constexpr auto VK_7            = 0x08;
        constexpr auto VK_8            = 0x09;
        constexpr auto VK_9            = 0x0A;
        constexpr auto VK_0            = 0x0B;
        constexpr auto VK_MINUS        = 0x0C;
        constexpr auto VK_EQUALS       = 0x0D;
        constexpr auto VK_BACKSPACE    = 0x0E;
        constexpr auto VK_TAB          = 0x0F;
        constexpr auto VK_Q            = 0x10;
        constexpr auto VK_W            = 0x11;
        constexpr auto VK_E            = 0x12;
        constexpr auto VK_R            = 0x13;
        constexpr auto VK_T            = 0x14;
        constexpr auto VK_Y            = 0x15;
        constexpr auto VK_U            = 0x16;
        constexpr auto VK_I            = 0x17;
        constexpr auto VK_O            = 0x18;
        constexpr auto VK_P            = 0x19;
        constexpr auto VK_PAREN_LEFT   = 0x1A;
        constexpr auto VK_PAREN_RIGHT  = 0x1B;
        constexpr auto VK_ENTER        = 0x1C;
        constexpr auto VK_CTRL         = 0x1D;
        constexpr auto VK_A            = 0x1E;
        constexpr auto VK_S            = 0x1F;
        constexpr auto VK_D            = 0x20;
        constexpr auto VK_F            = 0x21;
        constexpr auto VK_G            = 0x22;
        constexpr auto VK_H            = 0x23;
        constexpr auto VK_J            = 0x24;
        constexpr auto VK_K            = 0x25;
        constexpr auto VK_L            = 0x26;
        constexpr auto VK_SEMI         = 0x27;
        constexpr auto VK_APOSTROPHE   = 0x28;
        constexpr auto VK_BACKTICK     = 0x29;
        constexpr auto VK_LSHIFT       = 0x2A;
        constexpr auto VK_BACKSLASH    = 0x2B;
        constexpr auto VK_Z            = 0x2C;
        constexpr auto VK_X            = 0x2D;
        constexpr auto VK_C            = 0x2E;
        constexpr auto VK_V            = 0x2F;
        constexpr auto VK_B            = 0x30;
        constexpr auto VK_N            = 0x31;
        constexpr auto VK_M            = 0x32;
        constexpr auto VK_COMMA        = 0x33;
        constexpr auto VK_DOT          = 0x34;
        constexpr auto VK_SLASH        = 0x35;
        constexpr auto VK_RSHIFT       = 0x36;
        constexpr auto VK_NUMPAD_MUL   = 0x37;
        constexpr auto VK_LALT         = 0x38;
        constexpr auto VK_SPACE        = 0x39;
        constexpr auto VK_CAPSLOCK     = 0x3A;
        constexpr auto VK_F1           = 0x3B;
        constexpr auto VK_F2           = 0x3C;
        constexpr auto VK_F3           = 0x3D;
        constexpr auto VK_F4           = 0x3E;
        constexpr auto VK_F5           = 0x3F;
        constexpr auto VK_F6           = 0x40;
        constexpr auto VK_F7           = 0x41;
        constexpr auto VK_F8           = 0x42;
        constexpr auto VK_F9           = 0x43;
        constexpr auto VK_F10          = 0x44;
        constexpr auto VK_NUMLOCK      = 0x45;
        constexpr auto VK_SCROLLLOCK   = 0x46;
        constexpr auto VK_NUMPAD7      = 0x47;
        constexpr auto VK_NUMPAD8      = 0x48;
        constexpr auto VK_NUMPAD9      = 0x49;
        constexpr auto VK_NUMPAD_MINUS = 0x4A;
        constexpr auto VK_NUMPAD4      = 0x4B;
        constexpr auto VK_NUMPAD5      = 0x4C;
        constexpr auto VK_NUMPAD6      = 0x4D;
        constexpr auto VK_NUMPAD_PLUS  = 0x4E;
        constexpr auto VK_NUMPAD1      = 0x4F;
        constexpr auto VK_NUMPAD2      = 0x50;
        constexpr auto VK_NUMPAD3      = 0x51;
        constexpr auto VK_NUMPAD0      = 0x52;
        constexpr auto VK_NUMPAD_DOT   = 0x53;
        constexpr auto VK_F11          = 0x57;
        constexpr auto VK_F12          = 0x58;
        constexpr auto VK_MENU         = 0x5D;

        constexpr auto VK_EXTENDED     = 0xE0; // Extended key prefix
        constexpr auto VK_UNKNOWN      = 0xFF; // Unknown key
    }
}